In [1]:
#Name    :- Diwakar Prajapati
#Reg No. :- 24-27-25
# Programme: M.Tech(Data science)
# Assignment Number: 2

## Q1

In [2]:
import numpy as np 
var1 = np.arange(1,31)
print(var1)
print("\nshape=",np.shape(var1))
print("\ndimension =",np.ndim(var1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

shape= (30,)

dimension = 1


In [3]:
var2 = np.reshape(var1,(5,6))
print(var2)
print("\nshape=",np.shape(var2))
print("\ndimension =",np.ndim(var2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

shape= (5, 6)

dimension = 2


In [4]:
var3 = np.reshape(var1,(2,3,5))
print(var3)
print("\nshape=",np.shape(var3))
print("\ndimension =",np.ndim(var3))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]

shape= (2, 3, 5)

dimension = 3


In [5]:
var2[1, 0] = -1
print(var2)
#Looking at var1
print("\n var1 = ",var1)
#Looking at var3
print("\n var3 = ", var3)

[[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

 var1 =  [ 1  2  3  4  5  6 -1  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

 var3 =  [[[ 1  2  3  4  5]
  [ 6 -1  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


Clearly, when we set the first value in the second row of var2 to -1, var1 and var3 value is updated, since it modified the original array var1 then reshape() returns a view.

(i) Sum var3 over its second dimension and print the result.

In [6]:
result_1 = np.sum(var3, axis=1)
print(result_1)

[[18 13 24 27 30]
 [63 66 69 72 75]]


(ii) Sum var3 over its third dimension and print the result. 


In [7]:
result_2 = np.sum(var3, axis=2)
print(result_2)

[[ 15  32  65]
 [ 90 115 140]]


(iii) Sum var3 over both its first and third dimensions and print the result.

In [8]:
result_3 =np.sum(var3, axis=(0, 2))
print(result_3)

[105 147 205]


(i) Slice out the second row of var2 and print it


In [9]:
second_row = var2[1]
print(second_row)

[-1  8  9 10 11 12]


(ii) Slice out the last column of var2 using the -1 notation and print it. 

In [10]:
last_column = var2[:, -1]
print(last_column)

[ 6 12 18 24 30]


(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [11]:
top_right_submatrix = var2[0:2, -2:]
print(top_right_submatrix)

[[ 5  6]
 [11 12]]


## Q2


In [12]:

vector = np.arange(10)  

result = vector + 1
print(result)


[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
vector = np.arange(1,11)
column_vector = vector.reshape(10,1)
A = column_vector + vector
print(A)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [14]:
import numpy.random as npr

# Generate fake data set with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Calculate the mean and standard deviation along each column (feature)
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

# Standardize the data (zero mean, unit variance)
standardized_data = (data - mean) / std_dev

# Print the original and standardized data
print("Original Data:\n", data)
print("\nStandardized Data:\n", standardized_data)

Original Data:
 [[ 4.75829768  0.12633969  0.31771398  2.40450519  1.03403852]
 [ 0.79988681  4.24811584  3.05917112  0.30761587  1.14406681]
 [ 2.12057133  2.15490769  3.56259001  1.61196604  0.4061373 ]
 [ 0.49709437  0.36563017  0.19581922  0.08793309  0.42113588]
 [ 0.91577391  1.34512061  7.54840961  2.28772273  0.59941279]
 [ 1.88888243  0.51152624  2.64802745  0.91654733  1.26601301]
 [ 3.2708978   0.93905583  0.9354699   7.63347721  1.54583908]
 [ 2.01508099  1.50634477  1.32366351  4.36325436  4.86861822]
 [ 0.40532185  1.45655179  1.31927483  0.80268923  0.37699447]
 [ 0.37107542  0.35602219  1.44188514  0.22059782  1.07051639]
 [ 0.41126464  2.37297859  2.24393396  3.10837062  0.45092569]
 [ 1.24603573  0.48295938  2.6296266   1.00171651  0.67585893]
 [ 1.12246587  1.51182079  4.85791468  1.75989518  0.04319306]
 [ 0.10792199  2.89437596  0.17848554  1.54136018  1.42610452]
 [ 1.49017318  0.32578839  0.58168762  0.22410917  1.05274635]
 [ 0.78975057  0.41511973  0.39500896  

In [15]:
data = np.exp(npr.randn(50, 5))
print(data)

[[ 1.24196365  4.40032228  0.27149725  0.18414546  0.27785858]
 [ 0.91628926  3.18813459  3.04047553  5.69092236  2.31827061]
 [ 0.49001587  0.06068887  0.48728681  0.47545349  0.87775553]
 [ 1.25324726  4.2780453   0.05945124  2.47598637  1.52950414]
 [ 2.96243352  1.32096318  0.6214317   3.88398593  0.82166874]
 [ 5.12024386  0.95129184  1.90062121  0.58823827  0.60692815]
 [ 1.40705067  0.42474163  1.35382427 28.00747058  0.25043758]
 [ 3.4431919   1.05529918  3.05800592  1.26040405 18.70325835]
 [ 1.77376107  1.10206432  3.22959853  1.64200603  0.76734323]
 [ 1.93181436  2.85189613  0.79246499  0.26825497  0.96253971]
 [ 0.18439602  0.32960374  0.59768562  0.90628506  2.28646493]
 [ 1.74659264  1.69400141  1.766259    0.51082097  6.16211628]
 [ 1.54664315  0.61827845  0.20974617  1.7251494   2.69868815]
 [ 0.66230972  0.28524476  0.30075061  1.05430955  1.14007837]
 [ 1.15308339  0.94826662  2.88234922  0.53053551  1.27950684]
 [ 0.3913177   1.4249632   0.65053195  0.75940449  0.69

In [16]:
data = np.exp(npr.randn(50, 5))
mean_vector = np.mean(data, axis=0)
std_vector = np.std(data, axis=0)
print("Mean of each column:", mean_vector)
print("Standard deviation of each column:", std_vector)

Mean of each column: [1.71481485 2.32196614 1.21748307 1.39238232 1.96627608]
Standard deviation of each column: [1.67324294 2.79425437 1.25243293 1.15081928 1.96008502]


In [17]:
normalized = (data - mean_vector) / std_vector
#To verify
normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)
print("Mean of each column after normalization:", normalized_mean)
print("Standard deviation of each column after normalization:", normalized_std)

Mean of each column after normalization: [-4.68514116e-16 -3.39728246e-16  4.55191440e-17  1.64313008e-16
 -1.11022302e-17]
Standard deviation of each column after normalization: [1. 1. 1. 1. 1.]


## Q3


In [18]:
import numpy as np

def vandermonde_matrix(N):
    
    x = np.arange(1, N+1)
    
    
    vander_matrix = x[:, None] ** np.arange(N)
    
    return vander_matrix


N = 12
print(vandermonde_matrix(N))


[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [19]:
vander = vandermonde_matrix(N)
x = np.ones(N)

# Perform matrix-vector multiplication
b = np.dot(vander, x)

# Print the result
print("The vector b is:")
print(b)

The vector b is:
[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [20]:
from numpy.linalg import inv
x_actual = np.ones(N)
b = np.dot(vander, x_actual)
vander_inv = inv(vander)

x_solved = np.dot(vander_inv, b)

print("The solved vector x is:")
print(x_solved)

The solved vector x is:
[0.99559784 1.00491714 0.99946976 1.00000954 1.         0.99999917
 1.00000018 0.99999999 1.         1.         1.         1.        ]


In [21]:
from numpy.linalg import solve
x_solved = solve(vander, b)
print("The solved vector x using 'solve' is:")
print(x_solved)

The solved vector x using 'solve' is:
[1.0000114  0.99997033 1.00002961 0.99998507 1.00000423 0.9999993
 1.00000007 1.         1.         1.         1.         1.        ]


In [23]:
# the link of github file
